routes/web.php
<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use APP\Noticia;
use App\Providers\RouteServiceProvider;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $noticia = DB::table('noticia')->whereNull('fecha_expiracion')->orderBy('id', 'DESC')->paginate(6);
    $avisos = DB::table('noticia')->whereNotNull('fecha_expiracion')->orderBy('id', 'DESC')->paginate(4);
    return view('sbadmin.noticias',['noticia' =>$noticia],['avisos' =>$avisos]);
})
->middleware('guest')->name(RouteServiceProvider::LOGIN_ROUTE);



Route::post('/markasread', 'NotificacionController@markasread');
Route::post('/notifications', 'NotificacionController@notifications');

Route::get('/index', function () {
    return view('index');
})->name('index')->middleware('auth');

Auth::routes(['register' => false]);

Route::name('comite.')->prefix('comite')->group(function () {
    Route::resource('grupos', 'GrupoComiteController');
    Route::resource('grupos.integrantes', 'IntegranteComiteController')
        ->except('destroy');
    Route::resource('sesiones', 'SesionComiteController')
        ->parameters(['sesiones' => 'sesion']);
    Route::resource('sesiones.asistentes', 'AsistenciaController')
        ->parameters(['sesiones' => 'sesion'])
        ->only('index', 'create', 'store');

    Route::get('proyectos/{proyecto}/verificar', 'ProyectoGradoController@verificar')
        ->name('proyectos.verificar');
    Route::post('proyectos/{proyecto}/verificar/aprobado', 'ProyectoGradoController@aprobarVerificacion')
        ->name('proyectos.verificar.aprobado');
    Route::post('proyectos/{proyecto}/verificar/rechazado', 'ProyectoGradoController@rechazarVerificacion')
        ->name('proyectos.verificar.rechazado');
    Route::get('proyectos/calificador', 'ProyectoGradoController@mostrarAsignadosACalificador')
        ->name('proyectos.calificador');
    Route::resource('proyectos', 'ProyectoGradoController')
        ->except('edit', 'update', 'destroy');
    Route::resource('noticias', 'NoticiaController');
});

Route::name('proyectos.')->prefix('proyectos/{proyecto}')->group(function () {

    // Integrantes de proyecto
    Route::delete('integrantes', 'IntegranteProyectoController@destroy')
        ->name('integrantes.destroy');
    Route::resource('integrantes', 'IntegranteProyectoController')
        ->except('edit', 'update', 'destroy');

    // Seguimientos (observaciones)
    Route::resource('seguimientos', 'SeguimientoProyectoController')
        ->except('destroy');
});

Route::name('foro.')->prefix('foro')->group(function () {
    Route::resource('grupos', 'GrupoForoController');
    Route::resource('grupos.usuariosgrupo', 'UsuarioGrupoController');
    Route::resource('grupos.posts', 'PostController')->only("index");
    Route::get('buscargrupo', ['as' => 'buscargrupo', 'uses' => function () {
        return view('foro.grupos.buscargrupo');
    }]);
    Route::post('buscargrupo', ['as' => 'buscargrupo', 'uses' => 'GrupoForoController@buscarGrupo']);
    Route::resource('posts', 'PostController');
    Route::get('listarposts', ['as' => 'posts', 'uses' => 'PostController@cargarTodosPosts']);
    Route::get('descargararchivopost/{idarchivopost}', ['as' => 'descargararchivopost', 'uses' => 'PostController@descargarArchivoPost']);
    Route::get('descargararchivocomentario/{idarchivocomentario}', ['as' => 'descargararchivocomentario', 'uses' => 'PostController@descargarArchivoComentario']);
    Route::post(
        'posts/eliminarComentario/{comentario}',
        ['as' => 'posts.eliminarComentario', 'uses' => 'PostController@eliminarComentario']
    );
    Route::post(
        'posts/vincularComentario/{post}',
        ['as' => 'posts.vincularComentario', 'uses' => 'PostController@vincularComentarioPost']
    );
    Route::post(
        'posts/vincularComentarioAComentario/{comentario}',
        ['as' => 'posts.comentario.vincularComentario', 'uses' => 'PostController@vincularComentarioAComentario']
    );
});

Route::name('docente.')->prefix('docente')->group(function () {
    Route::resource('salones', 'SalonController')->parameters(['salones' => 'salon']);
    Route::resource('programas', 'ProgramaAcademicoController');
    Route::resource('materias', 'MateriaController');
    Route::resource('grupos', 'GrupoController');
    Route::resource('horarios', 'HorarioController');
    Route::resource('grupos.asistencia', 'AsistenciaDocenteController')->parameters(['asistencia' => 'asistencia']);
});

Route::get('docente/grupos/{materia}/horario', 'GrupoController@horarioPorMateria')->name('docente.grupos.horario');
Route::resource('docente', 'DocenteController')->except('destroy');

Route::get('derechosdegrado', 'DerechoGradoController@descargar')
    ->name('documento.derechosdegrado');

Route::get('proyectos/{proyecto}/documentacion', 'DocumentoController@index')->name('proyecto.documentacion');

Route::get('descargar-documentacion-final/{documento}', 'DocumentoController@comprimirYDescargar')->name('documentacion-zip');

Route::post('nuevo-comentario/{documento}','ComentarioDocumentoProyectoController')->name('nuevo-comentario');
Route::put('subir-archivo-proyecto-estudiante/{documento}','DocumentoController@subir_archivo_proyecto_estudiante')->name('subir-archivo-proyecto-estudiante');
Route::get('noticiav', 'NoticiaspublicasController@paginacion')->name('noticiav');
Route::get('avisosv', 'NoticiaspublicasController@avisosv')->name('avisosv');
Route::get('contenidov/{id}', 'NoticiaspublicasController@contenidov')->name('contenidov');
Route::get('contenidoa/{id}', 'NoticiaspublicasController@contenidoa')->name('contenidoa');

Route::resource('estudiantes', 'EstudianteController');
Route::get('historialNostas/{id}','NotasActualHistorialController@historialNotas')->name('historialNotas');
Route::get('notasActuales/{id}','NotasActualHistorialController@notasActuales')->name('notasActuales');
Route::get('registro-estudiante','RegistroEstudianteController@registroEstudiante')->name('registro-estudiante');
Route::get('lista-registro-ingreso-plataforma','EstudianteController@lista_registro_ingreso_plataforma')->name('lista-registro-ingreso-plataforma');
Route::post('crear-registro-ingreso-plataforma','RegistroEstudianteController@crear_registro_ingreso_plataforma')->name('crear-registro-ingreso-plataforma');
Route::put('aceptar-estudiante/{estudiante}','EstudianteController@aceptar_estudiante')->name('aceptar-estudiante');
Route::post('enviar-solicitud-proyecto-grado/{estudianteId}/{proyectoId}','ProyectoEstudianteController@enviar_solicitud_proyecto_grado')->name('enviar-solicitud-proyecto-grado');
Route::post('aceptar-solicitud-proyecto/{id}/{estudianteId}/{proyectoId}','ProyectoEstudianteController@aceptar_solicitud_proyecto')->name('aceptar-solicitud-proyecto');
Route::delete('eliminar-solicitud-proyecto/{id}/{proyectoId}','ProyectoEstudianteController@eliminar_solicitud_proyecto')->name('eliminar-solicitud-proyecto');
Route::resource('estudiantes', 'EstudianteController')->except('destroy');
Route::get('horarioEstudiante/{id}','HorarioHistorialController@horarioEstudiante')->name('horarioEstudiante');
Route::get('historialMaterias/{id}','HorarioHistorialController@historialMaterias')->name('historialMaterias');
Route::get('proyectos_inscripcion','ProyectoEstudianteController@proyectos_inscripcion')->name('proyectosInscripcion');
Route::post('aprobar-documento/{documento}','DocumentoController@aprobar_documento')->name('aprobar-documento');
Route::post('rechazar-documento/{documento}','DocumentoController@rechazar_documento')->name('rechazar-documento');
Route::put('cambiar-correo/{estudiante}','EstudianteController@cambiar_correo')->name('cambiar-correo');

resources/views/comite/proyectos/calificador.blade.php
@extends('sbadmin.index')

@section('sbadmin-body')
@panel
    @slot('titulo')

    <div class="clearfix">
        <div class="float-left"> <i class="fa fa-lightbulb"></i> Proyectos de grado | Calificador</div>

        @if (Auth::user()->docente)
            <div class="float-right">
                <a href="{{ route('comite.proyectos.index', ['misproyectos' => true]) }}" class="btn btn-uts btn-sm">Mis proyectos</a>
            </div>
        @endif
    </div>

    @endslot

    @if ($proyectos)
        @include('comite.proyectos.table')
    @else
        <div class="alert alert-info">
            No tiene proyectos asignados para calificar.
        </div>
    @endif

@endpanel
@endsection

resources/views/comite/proyectos/check.blade.php
@extends('sbadmin.index')

@section('sbadmin-body')
@panel
    @slot('icon') check-circle @endslot
    @slot('titulo') Verificar proyecto de grado @endslot

    <p>Verifique el siguiente proyecto de grado que ha sido registrado para que pueda ser aprobado para su desarrollo.</p>

    <div class="card">
        <h6 class="card-header"><b><i class="fas fa-info-circle"></i> Título</b></h6>
        <div class="card-body mb-0">
            <p class="mb-0">{{ $proyecto->nombre }}</p>
        </div>
    </div>

    <div class="card mt-3">
        <h6 class="card-header"><b><i class="fas fa-comment-alt"></i> Descripción</b></h6>
        <div class="card-body mb-0">
            <p class="mb-0">{{ $proyecto->descripcion }}</p>
        </div>
    </div>

    <div class="card mt-3">
        <h6 class="card-header"><b><i class="fas fa-user-tie"></i> Docente</b></h6>
        <div class="card-body mb-0">
            <p class="mb-0">{{ $proyecto->docente->nombres }} {{ $proyecto->docente->apellidos }}</p>
        </div>
    </div>

    <hr>

    <div class="float-left">
        <a href="{{ route('comite.proyectos.show', ['proyecto' => $proyecto->id]) }}" class="btn btn-secondary">
            <i class="fas fa-arrow-left"></i> Cancelar
        </a>
    </div>

    <div class="float-right">
        <button class="btn btn-danger" onclick="document.getElementById('rechazar').submit()">
            <i class="fas fa-times"></i> Rechazar
        </button>
        <button class="btn btn-uts" onclick="document.getElementById('aprobar').submit()">
            <i class="fas fa-check"></i> Aprobar/Admitir
        </button>

    </div>

    <form style="display: none;" id="aprobar" action="{{ route('comite.proyectos.verificar.aprobado', ['proyecto' => $proyecto->id]) }}" method="post">
        @csrf
    </form>
    <form style="display: none;" id="rechazar" action="{{ route('comite.proyectos.verificar.rechazado', ['proyecto' => $proyecto->id]) }}" method="post">
        @csrf
    </form>
@endpanel
@endsection

resources/views/comite/proyectos/create.blade.php
@extends('sbadmin.index')

@section('sbadmin-body')
@panel
    @slot('icon') lightbulb @endslot
    @slot('titulo') Registrar proyecto @endslot

    <form action="{{ route('comite.proyectos.store') }}" method="post">
        @csrf

        @include('comite.proyectos.form')
    </form>
@endpanel
@endsection

resources/views/comite/proyectos/form.blade.php
<p>Digite el siguiente formulario para registrar un proyecto de grado. Integrantes del comité de proyectos de grado se encargarán de evaluar la viabilidad del proyecto para ser aprobado y desarrollado.</p>

@include('partials.forms.error')

<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label for="nombre">Título o nombre del proyecto *</label>
            <textarea name="nombre" id="nombre" required rows="3" class="form-control">{{ $proyecto->nombre }}</textarea>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="form-group">
            <label for="descripcion">Descripción</label>
            <textarea name="descripcion" id="descripcion" rows="10" class="form-control">{{ $proyecto->descripcion }}</textarea>
        </div>
    </div>
</div>

<div class="float-right">
    <a href="{{ route('comite.proyectos.index') }}" class="btn btn-secondary">
        <i class="fas fa-times"></i> Cancelar
    </a>
    @btnreset @endbtnreset
    @btnsubmit @endbtnsubmit
</div>

resources/views/comite/proyectos/index.blade.php
@extends('sbadmin.index')

@section('sbadmin-body')
@panel
    @slot('titulo')

    <div class="clearfix">
        <div class="float-left"> <i class="fa fa-lightbulb"></i> Proyectos de grado</div>

        @if (Auth::user()->docente)
            <div class="float-right ml-2">
                <a href="{{ route('comite.proyectos.index', ['misproyectos' => true]) }}" class="btn btn-uts btn-sm">Mis proyectos</a>
            </div>

            <div class="float-right">
                <a href="{{ route('comite.proyectos.calificador') }}" class="btn btn-uts btn-sm">Calificar proyectos</a>
            </div>
        @endif
    </div>

    @endslot

    @if (!request()->misproyectos && !request()->miproyecto)
    <p>Se lista a continuación todos los proyectos de grado registrados en los programas de tecnología e ingeniería de la Coordinación de Sistemas.</p>
    @elseif (request()->miproyecto && Auth::user()->estudiante)
    <p>Listando proyecto al que está inscrito.</p>
    @endif

    @include('partials.forms.deleted')

    @if ($proyectos->count())
        @if (request()->misproyectos && Auth::user()->docente)
        <div class="alert alert-info">
            <p class="mb-0">Listando mis proyectos, para volver a ver todos los proyectos haz clic <a class="text-primary" href="{{ route('comite.proyectos.index') }}">aquí</a>.</p>
        </div>
        @endif

        @include('comite.proyectos.table')
    @else
        <div class="alert alert-info">
            @if (request()->misproyectos && Auth::user()->docente)
            <p>Listando mis proyectos, para volver a ver todos los proyectos haz clic <a class="text-primary" href="{{ route('comite.proyectos.index') }}">aquí</a>.</p>
            @endif

            <p class="mb-0">
                No hay proyectos registrados. @if (Auth::user()->docente)
                Haz clic <a href="{{ route('comite.proyectos.create') }}" class="text-primary">aquí</a> para registrar uno nuevo. Cualquier docente puede registrar un proyecto de grado.
                @endif
            </p>
        </div>
    @endif

@endpanel
@endsection

resources/views/comite/proyectos/show.blade.php
@extends('sbadmin.index')

@section('sbadmin-body')
@panel
    @slot('icon') lightbulb @endslot
    @slot('titulo') Proyecto de grado @endslot

    @include('partials.forms.saved')

    <table class="table table-bordered">
        <thead>
            <tr>
                <th colspan="4" class="text-center">
                    <i class="fas fa-info-circle"></i> <i>Información del proyecto de grado</i>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Nombre</th>
                <td colspan="3">{{ $proyecto->nombre }}</td>
            </tr>
            <tr>
                <th>Descripción</th>
                <td colspan="3">{{ $proyecto->descripcion }}</td>
            </tr>
            <tr>
                <th>Estado</th>
                <td>{{ $proyecto->estadoProyecto->nombre }}</td>
                <th>Docente</th>
                <td>{{ $proyecto->docente->nombres }} {{ $proyecto->docente->apellidos }}</td>
            </tr>
            <tr>
                <th>Fecha de registro</th>
                <td>{{ $proyecto->created_at }}</td>
                <th>Fecha de modificación</th>
                <td>{{ $proyecto->updated_at }}</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">
                    <a href="{{ route('comite.proyectos.index') }}" class="btn btn-secondary">
                        <i class="fas fa-list"></i> Ver proyectos
                    </a>
                    @if (Auth::user()->puedeVerificarProyecto($proyecto))
                        <a href="{{ route('comite.proyectos.verificar', ['proyecto' => $proyecto->id]) }}" class="btn btn-info">
                            <i class="fas fa-check"></i> Verificar
                        </a>
                    @endif
                    @if ($proyecto->revisado)
                    <a href="{{ route('proyectos.integrantes.index', ['proyecto'=> $proyecto->id]) }}" class="btn btn-secondary">
                        <i class="fas fa-users"></i> Ver integrantes del proyecto
                    </a>
                    @endif
                    @if (Auth::user()->puedeAgregarSeguimientosAlProyecto($proyecto))
                    <a href="{{ route('proyectos.seguimientos.index', ['proyecto'=> $proyecto->id]) }}" class="btn btn-info">
                        <i class="fas fa-clipboard-list"></i> Ver seguimientos
                    </a>
                    @endif
                </td>
            </tr>
        </tfoot>
    </table>
@endpanel
@endsection

resources/views/comite/proyectos/table.blade.php
<table class="table table-bordered table-sm table-striped table-hover">
    <thead>
        <tr>
            <th>Título</th>
            <th>Estado</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($proyectos as $p)
            <tr>
                <td>{{ $p->nombre }}</td>
                <td>{{ $p->estadoProyecto->nombre }}</td>
                <td>
                    <a href="{{ route('comite.proyectos.show', ['proyecto' => $p->id]) }}" class="btn btn-sm btn-primary" title="Mostrar detalles">
                        <i class="fas fa-eye"></i>
                    </a>
                    @if (Auth::user()->puedeVerificarProyecto($p))
                        <a href="{{ route('comite.proyectos.verificar', ['proyecto' => $p->id]) }}" class="btn btn-sm btn-info" title="Verificar">
                            <i class="fas fa-check"></i>
                        </a>
                    @endif
                    @if (Auth::user()->esIntegranteProyecto($p))
                        <a href="{{ route('proyecto.documentacion', ['proyecto' => $p->id]) }}" class="btn btn-sm btn-info" title="Documentacion">
                            <i class="fas fa-folder-open"></i>
                        </a>
                    @endif
                </td>
            </tr>
        @endforeach
    </tbody>
</table>