routes/web.php
<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use APP\Noticia;
use App\Providers\RouteServiceProvider;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $noticia = DB::table('noticia')->whereNull('fecha_expiracion')->orderBy('id', 'DESC')->paginate(6);
    $avisos = DB::table('noticia')->whereNotNull('fecha_expiracion')->orderBy('id', 'DESC')->paginate(4);
    return view('sbadmin.noticias',['noticia' =>$noticia],['avisos' =>$avisos]);
})
->middleware('guest')->name(RouteServiceProvider::LOGIN_ROUTE);



Route::post('/markasread', 'NotificacionController@markasread');
Route::post('/notifications', 'NotificacionController@notifications');

Route::get('/index', function () {
    return view('index');
})->name('index')->middleware('auth');

Auth::routes(['register' => false]);

Route::name('comite.')->prefix('comite')->group(function () {
    Route::resource('grupos', 'GrupoComiteController');
    Route::resource('grupos.integrantes', 'IntegranteComiteController')
        ->except('destroy');
    Route::resource('sesiones', 'SesionComiteController')
        ->parameters(['sesiones' => 'sesion']);
    Route::resource('sesiones.asistentes', 'AsistenciaController')
        ->parameters(['sesiones' => 'sesion'])
        ->only('index', 'create', 'store');

    Route::get('proyectos/{proyecto}/verificar', 'ProyectoGradoController@verificar')
        ->name('proyectos.verificar');
    Route::post('proyectos/{proyecto}/verificar/aprobado', 'ProyectoGradoController@aprobarVerificacion')
        ->name('proyectos.verificar.aprobado');
    Route::post('proyectos/{proyecto}/verificar/rechazado', 'ProyectoGradoController@rechazarVerificacion')
        ->name('proyectos.verificar.rechazado');
    Route::get('proyectos/calificador', 'ProyectoGradoController@mostrarAsignadosACalificador')
        ->name('proyectos.calificador');
    Route::resource('proyectos', 'ProyectoGradoController')
        ->except('edit', 'update', 'destroy');
    Route::resource('noticias', 'NoticiaController');
});

Route::name('proyectos.')->prefix('proyectos/{proyecto}')->group(function () {

    // Integrantes de proyecto
    Route::delete('integrantes', 'IntegranteProyectoController@destroy')
        ->name('integrantes.destroy');
    Route::resource('integrantes', 'IntegranteProyectoController')
        ->except('edit', 'update', 'destroy');

    // Seguimientos (observaciones)
    Route::resource('seguimientos', 'SeguimientoProyectoController')
        ->except('destroy');
});

Route::name('foro.')->prefix('foro')->group(function () {
    Route::resource('grupos', 'GrupoForoController');
    Route::resource('grupos.usuariosgrupo', 'UsuarioGrupoController');
    Route::resource('grupos.posts', 'PostController')->only("index");
    Route::get('buscargrupo', ['as' => 'buscargrupo', 'uses' => function () {
        return view('foro.grupos.buscargrupo');
    }]);
    Route::post('buscargrupo', ['as' => 'buscargrupo', 'uses' => 'GrupoForoController@buscarGrupo']);
    Route::resource('posts', 'PostController');
    Route::get('listarposts', ['as' => 'posts', 'uses' => 'PostController@cargarTodosPosts']);
    Route::get('descargararchivopost/{idarchivopost}', ['as' => 'descargararchivopost', 'uses' => 'PostController@descargarArchivoPost']);
    Route::get('descargararchivocomentario/{idarchivocomentario}', ['as' => 'descargararchivocomentario', 'uses' => 'PostController@descargarArchivoComentario']);
    Route::post(
        'posts/eliminarComentario/{comentario}',
        ['as' => 'posts.eliminarComentario', 'uses' => 'PostController@eliminarComentario']
    );
    Route::post(
        'posts/vincularComentario/{post}',
        ['as' => 'posts.vincularComentario', 'uses' => 'PostController@vincularComentarioPost']
    );
    Route::post(
        'posts/vincularComentarioAComentario/{comentario}',
        ['as' => 'posts.comentario.vincularComentario', 'uses' => 'PostController@vincularComentarioAComentario']
    );
});

Route::name('docente.')->prefix('docente')->group(function () {
    Route::resource('salones', 'SalonController')->parameters(['salones' => 'salon']);
    Route::resource('programas', 'ProgramaAcademicoController');
    Route::resource('materias', 'MateriaController');
    Route::resource('grupos', 'GrupoController');
    Route::resource('horarios', 'HorarioController');
    Route::resource('grupos.asistencia', 'AsistenciaDocenteController')->parameters(['asistencia' => 'asistencia']);
});

Route::get('docente/grupos/{materia}/horario', 'GrupoController@horarioPorMateria')->name('docente.grupos.horario');
Route::resource('docente', 'DocenteController')->except('destroy');

Route::get('derechosdegrado', 'DerechoGradoController@descargar')
    ->name('documento.derechosdegrado');

Route::get('proyectos/{proyecto}/documentacion', 'DocumentoController@index')->name('proyecto.documentacion');

Route::get('descargar-documentacion-final/{documento}', 'DocumentoController@comprimirYDescargar')->name('documentacion-zip');

Route::post('nuevo-comentario/{documento}','ComentarioDocumentoProyectoController')->name('nuevo-comentario');
Route::put('subir-archivo-proyecto-estudiante/{documento}','DocumentoController@subir_archivo_proyecto_estudiante')->name('subir-archivo-proyecto-estudiante');
Route::get('noticiav', 'NoticiaspublicasController@paginacion')->name('noticiav');
Route::get('avisosv', 'NoticiaspublicasController@avisosv')->name('avisosv');
Route::get('contenidov/{id}', 'NoticiaspublicasController@contenidov')->name('contenidov');
Route::get('contenidoa/{id}', 'NoticiaspublicasController@contenidoa')->name('contenidoa');

Route::resource('estudiantes', 'EstudianteController');
Route::get('historialNostas/{id}','NotasActualHistorialController@historialNotas')->name('historialNotas');
Route::get('notasActuales/{id}','NotasActualHistorialController@notasActuales')->name('notasActuales');
Route::get('registro-estudiante','RegistroEstudianteController@registroEstudiante')->name('registro-estudiante');
Route::get('lista-registro-ingreso-plataforma','EstudianteController@lista_registro_ingreso_plataforma')->name('lista-registro-ingreso-plataforma');
Route::post('crear-registro-ingreso-plataforma','RegistroEstudianteController@crear_registro_ingreso_plataforma')->name('crear-registro-ingreso-plataforma');
Route::put('aceptar-estudiante/{estudiante}','EstudianteController@aceptar_estudiante')->name('aceptar-estudiante');
Route::post('enviar-solicitud-proyecto-grado/{estudianteId}/{proyectoId}','ProyectoEstudianteController@enviar_solicitud_proyecto_grado')->name('enviar-solicitud-proyecto-grado');
Route::post('aceptar-solicitud-proyecto/{id}/{estudianteId}/{proyectoId}','ProyectoEstudianteController@aceptar_solicitud_proyecto')->name('aceptar-solicitud-proyecto');
Route::delete('eliminar-solicitud-proyecto/{id}/{proyectoId}','ProyectoEstudianteController@eliminar_solicitud_proyecto')->name('eliminar-solicitud-proyecto');
Route::resource('estudiantes', 'EstudianteController')->except('destroy');
Route::get('horarioEstudiante/{id}','HorarioHistorialController@horarioEstudiante')->name('horarioEstudiante');
Route::get('historialMaterias/{id}','HorarioHistorialController@historialMaterias')->name('historialMaterias');
Route::get('proyectos_inscripcion','ProyectoEstudianteController@proyectos_inscripcion')->name('proyectosInscripcion');
Route::post('aprobar-documento/{documento}','DocumentoController@aprobar_documento')->name('aprobar-documento');
Route::post('rechazar-documento/{documento}','DocumentoController@rechazar_documento')->name('rechazar-documento');
Route::put('cambiar-correo/{estudiante}','EstudianteController@cambiar_correo')->name('cambiar-correo');

app/Docente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;

class Docente extends Model
{
    protected $table = 'docente';

    protected $fillable = [ 'documento', 'nombres', 'apellidos', 'correo', 'genero', 'fecha_nacimiento', 'archivo', 'horario', 'clasificacion_id', 'tipo_documento_id', 'usuario_id'];

    public function clasificacion()
    {
        return $this->belongsTo(Clasificacion::class);
    }

    public function tipoDocumento()
    {
        return $this->belongsTo(TipoDocumento::class);
    }

    public function grupos()
    {
        return $this->hasMany(Grupo::class);
    }

    public function usuario()
    {
        return $this->belongsTo(User::class, 'usuario_id');
    }

    public function integranteComite()
    {
        return $this->hasOne(IntegranteComite::class);
    }

    public static function comprobarDocente($id)
    {
        if (Auth::user()->tieneRolCoordinador()) {
            return true;
        } elseif(Auth::user()->docente->id != $id) {
            return abort(404);
        }
        return true;
    }
}

app/Http/Controllers/DocenteController.php
<?php

namespace App\Http\Controllers;

use App\Clasificacion;
use App\Docente;
use App\Horario;
use App\User;
use App\Http\Requests\DocenteRequest;
use Illuminate\Support\Facades\Storage;
use App\TipoDocumento;
use Illuminate\Http\Request;

class DocenteController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
        $this->middleware('docente');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (auth()->user()->tieneRolCoordinador()) {
            $docentes = Docente::latest()->get();
        } else {
            $docentes = Docente::where('id', auth()->user()->docente->id)->latest()->get();
        }
        return view('docente.index', compact('docentes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $clasificaciones = Clasificacion::all();
        $tiposDocumento = TipoDocumento::all();
        $docente = new Docente();
        return view('docente.create', compact('clasificaciones', 'tiposDocumento', 'docente'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DocenteRequest $request)
    {
        // $docente = new Docente($request->all());
        // $docente->clasificacion_id = $request->clasificacion;
        // $docente->tipo_documento_id = $request->tipo_documento;
        // // $docente->usuario_id = auth()->id();
        // $docente->usuario_id = auth()->docente()->id;
        // $docente->save();
        // return redirect()
        //     ->route('docente.show', ['docente' => $docente->id])
        //     ->with(['saved' => true]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        Docente::comprobarDocente($id);
        $docente = Docente::findOrFail($id);
        return view('docente.show', compact('docente'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Docente::comprobarDocente($id);
        $docente = Docente::findOrFail($id);
        $clasificaciones = Clasificacion::all();
        $tiposDocumento = TipoDocumento::all();
        return view('docente.update', compact('clasificaciones', 'tiposDocumento', 'docente'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(DocenteRequest $request, $id)
    {
        Docente::comprobarDocente($id);
        $docente = Docente::findOrFail($id);

        if($request->hasFile('archivo')){

            Storage::delete('public/docente/'.$docente->documento.'/'.$docente->archivo);
            $archivo = $request->file('archivo');
            $nombreArchivo = $archivo->getClientOriginalName();
            $request->archivo->storeAs('public/docente/'.$docente->documento, $nombreArchivo);
            $docente->archivo = $nombreArchivo;
        }

        if($request->hasFile('horario')){

            Storage::delete('public/docente/'.$docente->documento.'/'.$docente->horario);
            $horario = $request->file('horario');
            $nombreHorario = $horario->getClientOriginalName();
            $request->horario->storeAs('public/docente/'.$docente->documento, $nombreHorario);
            $docente->horario = $nombreHorario;
        }
        
        $docente->documento = $request->documento;
        $docente->nombres = $request->nombres;
        $docente->apellidos = $request->apellidos;
        $docente->fecha_nacimiento = $request->fecha_nacimiento;
        $docente->genero = $request->genero;
        $docente->correo = $request->correo;
        // $docente->clasificacion_id = $request->clasificacion;
        // $docente->tipo_documento_id = $request->tipo_documento;
        $docente->save();
        return redirect()
            ->route('docente.show', ['docente' => $docente->id])
            ->with(['saved' => true]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Docente::destroy($id);

        return redirect()
            ->route('docente.index')
            ->with(['deleted' => true]);
    }

    public function horario()
    {
        $horarioDocente = Horario::join('grupo', 'grupo.id', '=', 'horario.grupo_id')
            // ->where('grupo.docente_id', auth()->docente()->id)
            ->where('grupo.docente_id', auth()->user()->docente->id)
            ->get();

        return view('docente.horario', compact('horarioDocente'));
    }
}

resources/views/docente/programas/create.blade.php
@extends('sbadmin.index')

@section('sbadmin-body')
@panel
    @slot('icon') user-friends @endslot
    @slot('titulo') Registrar programa académico @endslot

    <form action="{{ route('docente.programas.store') }}" method="post">
        @csrf

        @include('docente.programas.form')
    </form>
@endpanel
@endsection

resources/views/docente/programas/form.blade.php
<p>Digite el siguiente formulario, los campos con * son obligatorios.</p>

@include('partials.forms.error')

<div class="row">
    <div class="col-sm-12 col-md-8">
        <div class="form-group">
            <label for="nombre">Nombre del programa académico *</label>
            <input
                id="nombre"
                name="nombre"
                value="{{ old('nombre', $programa->nombre) }}"
                type="text"
                class="form-control @error('nombre') is-invalid @enderror">

            @error('nombre')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
            @enderror
        </div>
    </div>
    <div class="col-sm-12 col-md-4">
        <div class="form-group">
            <label for="tipoPrograma">Tipo de programa *</label>
            <select value="{{ old('tipo_programa', $programa->tipo_programa_id) }}" name="tipo_programa" class="custom-select @error('tipo_programa') is-invalid @enderror" id="tipo_programa">
                <option value="">-- Seleccionar --</option>
                @foreach ($tiposPrograma as $tipo)
                    <option
                    @if (old('tipo_programa', $programa->tipo_programa_id) == $tipo->id) selected="selected" @endif
                    value="{{ $tipo->id }}">{{ $tipo->nombre }}</option>
                @endforeach
            </select>
            @error('tipo_programa')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
            @enderror
        </div>
    </div>
    <div class="col-sm-12 col-md-4">
        <div class="form-group">
            <label for="facultad">Facultad *</label>
            <select value="{{ old('facultad', $programa->facultad_id) }}" name="facultad" class="custom-select @error('facultad') is-invalid @enderror" id="facultad">
                <option value="">-- Seleccionar --</option>
                @foreach ($facultades as $facultad)
                    <option
                    @if (old('facultad', $programa->facultad_id) == $facultad->id) selected="selected" @endif
                    value="{{ $facultad->id }}">{{ $facultad->nombre }}</option>
                @endforeach
            </select>
            @error('facultad')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
            @enderror
        </div>
    </div>
</div>

<hr>

@if ($programa->id)
<div class="float-left">
    @btndelete @endbtndelete
</div>
@endif

<div class="float-right">
    <a href="{{ route('docente.programas.index') }}" class="btn btn-secondary">
        <i class="fas fa-times"></i> Cancelar
    </a>
    @btnreset @endbtnreset
    @btnsubmit @endbtnsubmit
</div>

resources/views/docente/programas/index.blade.php
@extends('sbadmin.index')

@section('sbadmin-body')
@panel
    @slot('icon') user-friends @endslot
    @slot('titulo') Programas académicos @endslot

    <p>Se lista a continuación los programas académicos registrados.</p>

    @include('partials.forms.deleted')

    @if (count($programas))
        @include('docente.programas.table')
    @else
        <div class="alert alert-info">
            No hay programas académicos registrados. Haz clic <a href="{{ route('docente.programas.create') }}" class="text-primary">aquí</a> para registrar uno nuevo.
        </div>
    @endif

@endpanel
@endsection

resources/views/docente/programas/show.blade.php
@extends('sbadmin.index')

@section('sbadmin-body')
@panel
    @slot('icon') user-friends @endslot
    @slot('titulo') Programa académico @endslot

    @include('partials.forms.saved')

    <table class="table table-bordered">
        <thead>
            <tr>
                <th colspan="4" class="text-center">
                    <i class="fas fa-info-circle"></i> <i>Información del programa académico</i>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Nombre</th>
                <td colspan="3">{{ $programa->nombre }}</td>
            </tr>
            <tr>
                <th>Tipo de Programa</th>
                <td colspan="3">{{ $programa->tipoPrograma->nombre }}</td>
            </tr>
            <tr>
                <th>Facultad</th>
                <td>{{ $programa->facultad->nombre }}</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4">
                    <a href="{{ route('docente.programas.index') }}" class="btn btn-secondary">
                        <i class="fas fa-list"></i> Ver programas académicos
                    </a>
                    <a href="{{ route('docente.programas.edit', ['programa'=> $programa->id]) }}" class="btn btn-info">
                        <i class="fas fa-edit"></i> Editar
                    </a>
                </td>
            </tr>
        </tfoot>
    </table>
@endpanel
@endsection

resources/views/docente/programas/table.blade.php
<table class="table table-bordered table-sm table-striped table-hover">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Tipo de programa</th>
            <th>Facultad</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($programas as $p)
            <tr>
                <td>{{ $p->nombre }}</td>
                <td>{{ $p->tipoPrograma->nombre }}</td>
                <td>{{ $p->facultad->nombre }}</td>
                <td>
                    <a href="{{ route('docente.programas.show', ['programa' => $p->id]) }}" class="btn btn-sm btn-primary" title="Mostrar detalles">
                        <i class="fas fa-eye"></i>
                    </a>
                    <a href="{{ route('docente.programas.edit', ['programa' => $p->id]) }}" class="btn btn-sm btn-info" title="Editar registro">
                        <i class="fas fa-edit"></i>
                    </a>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

resources/views/docente/programas/update.blade.php
@extends('sbadmin.index')

@section('sbadmin-body')
@panel
    @slot('icon') user-friends @endslot
    @slot('titulo') Editar programa académico @endslot

    <form action="{{ route('docente.programas.update', ['programa' => $programa->id]) }}" method="post">
        @csrf
        @method('PUT')

        @include('docente.programas.form')
    </form>
@endpanel

@include('partials.delete', ['route' => route('docente.programas.destroy', ['programa' => $programa->id])])
@endsection